### ISSUE TITLE
Please provide...

### ISSUE THREAD

**Issue by SebiTimeWaster** [afch/NixieClock#1]
...schematics for NCM107 v1.1 and NCT412 V1.0.

also in the source code there is a "DHVpin" specified but in all instances commented out, is this not usable (anymore) on the aforementioned boards? 
the pin number for the DHVpin is now used for the first anode pin, is there a new pin that switches the HV line?

**Comment by SebiTimeWaster** [comment]
For your interest: https://github.com/SebiTimeWaster/Slave-Nixie-Clock

If i could switch off the HV line it would be complete...

**Comment by afch** [comment]
In this version SHDN input is grounded.
If You need to turn off all tubes, You need to send over SPI
  int blank=B00000000; <-for NCT318 tubes board
or
  int blank=B00000000; <- any others boards 4xx series
  SPI.transfer(blank);
  SPI.transfer(blank);
  SPI.transfer(blank);
  SPI.transfer(blank);
  SPI.transfer(blank);
  SPI.transfer(blank);
  SPI.transfer(blank);
  SPI.transfer(blank);

2017-04-03 0:55 GMT+03:00 TimeWaster <notifications@github.com>:

**Comment by afch** [comment]
Very useful modifications!!!!!! Thank You!!!

2017-04-06 17:06 GMT+03:00 Alexej Fomin <fominalec@gmail.com>:

**Comment by SebiTimeWaster** [comment]
too bad the pin is grounded. it felt only right to turn off HV while the clock is in standby to save some mA/µA.

i also just added a 3d printed stand to my repo, this could be also useful to other users of the IN-12 version, feel free to copy it (MIT license), i will add photos in a moment.

**Comment by afch** [comment]
Thank You for stands, we will try it...
We work on new version of MCU board - NCM108 where this input will be
connected to microcontroller again.

2017-04-06 17:48 GMT+03:00 TimeWaster <notifications@github.com>:

**Comment by SebiTimeWaster** [comment]
cool. if i would be asked to breathe a wish i would say bring the HV switch IC's to the NCT board and don't cycle through the tubes separately. (like you did on the aurdino shield) this would make the display brighter and you could dim it via software without producing flicker.

anyway, i would still be happy if you could provide schematics for NCM107 v1.1 and NCT412 V1.0.

**Comment by afch** [comment]
??? HMMMM....????
On both our shields (NCS314 and NCS312) we use full static mode and don't
switching between tubes!!!

See shematics in attachments:

2017-04-06 18:19 GMT+03:00 TimeWaster <notifications@github.com>:

**Comment by afch** [comment]
Scheme was added to github

2017-04-06 19:00 GMT+03:00 Alexej Fomin <fominalec@gmail.com>:

**Comment by SebiTimeWaster** [comment]
oh now i get it, i meant actually that, the shields are using "static mode", in contrast to to NCM107.

thanx for the schematics!

**Comment by afch** [comment]
These shields only in blue color...

**Comment by SebiTimeWaster** [comment]
here are finally the pictures of the stand:
https://github.com/SebiTimeWaster/Slave-Nixie-Clock/blob/master/Nixie.png
https://github.com/SebiTimeWaster/Slave-Nixie-Clock/blob/master/Nixie_Stand.png
feel free to use them.

**Comment by SebiTimeWaster** [comment]
http://www.thingiverse.com/thing:2232491

**Comment by afch** [comment]
On real photos this stands looks even more better!

2017-04-06 23:18 GMT+03:00 TimeWaster <notifications@github.com>:
