### ISSUE TITLE
"MCU Board NCM109 v1.x for Tubes board NCT4xx" doesn't compile 

### ISSUE THREAD

**Issue by SensoriumEmbedded** [afch/NixieClock#5]
"MCU Board NCM109 v1.x for Tubes board NCT4xx" doesn't compile correctly. Had to replace SPI_Init(); with SPI.begin();
After this mod it compiles and works correctly.

**Comment by SensoriumEmbedded** [comment]
I take that back, it now compiles, but does not display correctly...

**Comment by SensoriumEmbedded** [comment]
Had to add the correct SPI init line as well as the .begin()
    SPI.beginTransaction(SPISettings(2000000, LSBFIRST, SPI_MODE2));  //for HV5222, or...
    SPI.beginTransaction(SPISettings(2000000, MSBFIRST, SPI_MODE2));  //for HV5122
Now it compiles and works!

**Comment by afch** [comment]
Fixed...
